# # Set global options
data_dir = "/var/lib/vector"

[sources.netology_source]
type = "docker_logs"
docker_host = "/var/run/docker.sock"
include_containers = [ 
    "practice_gateway", 
    "practice_uploader", 
    "practice_security"]

[transforms.netology_modify]
type = "remap"
inputs = ["netology_source"]
source = '''
  del(.label)
'''

[sinks.elastic]
type = "elasticsearch"
inputs = [ "netology_modify" ]
endpoint = "http://elastic-hot:9200"
mode = "bulk"
suppress_type_name = true
compression = "none"


[sinks.elastic.bulk]
index = "vector-%Y-%m-%d"

# [sinks.my_sink_id]
# type = "console"
# inputs = [ "netology_modify" ]
# encoding = "json"
# target = "stdout"